# Generated by Django 3.1.3 on 2020-12-01 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jamup', '0002_auto_20201130_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='profile',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='jamup.profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='content_type',
            field=models.CharField(default='', help_text='The MIMEType of the file', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.BinaryField(default=False, editable=True, null=True),
        ),
    ]
