# Generated by Django 3.1.3 on 2020-12-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamup', '0006_auto_20201201_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
